### ISSUE TITLE
Change E2 Functions to return Vector/Angle userdata

### ISSUE THREAD

**Issue by vurvdev** [dvdvideo1234/E2PistonTiming#2]
This is an issue to warn that any functions that return the ``vector`` or ``angle`` E2 type will be broken if they aren't converted from returning lua tables of three numbers, for example ``{0, 0, 0}`` to instead returning the glua userdata ``Vector(0, 0, 0)`` or ``Angle(0, 0, 0)``.

This is part of an effort to ensure the amount of extensions broken by merging wiremod/wire#2399 is minimal.

**Comment by dvdvideo1234** [comment]
@Vurv78 

Hey, questions:
1. How can this affect [the other vector return types](https://github.com/dvdvideo1234/ControlSystemsE2/wiki/Data-types) like V2 or V4 for example?
2. Can I assume automatically that wire arguments will pass `Vector()` and `Angle()` user-data ?

**Comment by vurvdev** [comment]
1. It won't, since those two aren't actual glua types nor expected to be used that way, so those will remain the same.

2. After the PR is merged, yes, this was done in order to allow for that as an optimization, for example passing an e2 vector directly to applyoffsetforce

**Comment by dvdvideo1234** [comment]
@Vurv78 

E2 code creating a flash tracer. Assuming this will be OK after the PR is merged. I will test using your branch if fails.

```lua
T = E:setFTrace(E:massCenterL(),vec(0,0,1), -225)
```
Internally calls:
```lua
__e2setcost(20)
e2function ftrace entity:setFTrace(vector vP, vector vD, number nL)
  return newTracer(self, this, vP, vD, nL)
end
```
Passes table vector to `newTracer`:
```lua
if(vDir and ncDir > 0) then oFTrc.mDir:Set(vDir) end -- Local tracer direction to read
```
Results in:
```
[AdvDupe2NotifyPaste]	 Player: [Sk$Bh]Trick or treat KID! Pasted File, stcontrol_ftrace with, 6 Entities and 5 Constraints.
[AdvDupe2Notify]	Pasting...
sv: Expression 2 (adaptive fiter OOP): entities/gmod_wire_expression2/core/custom/ftrace.lua:460: bad argument #1 to 'Set' (Vector expected, got table)
```

**Comment by vurvdev** [comment]
Are you testing with both wiremod/wire#2399 and wiremod/wire-extras#112 ? And no other addons? I could have missed some functions to port over (especially those that aren't using the e2 preprocessor)

**Comment by dvdvideo1234** [comment]
Nope. I was testing with the general wire version ;) That explains a lot. Is the PR gonna be merged soon? I think of keeping my mods on a branches now. When the new wire goes to the WS, I'll just merge ;)

**Comment by vurvdev** [comment]
It won't be on the workshop for a while probably but I might merge it later today or tomorrow. Will just fix any bugs that come from merging

**Comment by vurvdev** [comment]
Just to let you know it has been pushed to the workshop now
